#!/usr/bin/env python3
"""stele - regenerate TASKS.md from task files, and validate the invariants.

Task files are the source of truth. TASKS.md is a rendered index; fix drift by
regenerating it, never by editing it.

Usage:
    python3 index.py                          regenerate, finding stele/ upward from cwd
    python3 index.py --root ./stele           point at a stele/ directory explicitly
    python3 index.py --root ./stele --check    exit 1 on drift or a broken invariant
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# A step heading marked open. Anchored to `###` so the word cannot match in prose.
OPEN_STEP = re.compile(r"^###.*\[\s*open\s*\]", re.MULTILINE | re.IGNORECASE)

FIELDS = ("id", "title", "status", "last_modified_by", "created_at", "updated_at")

HEADER = (
    "<!-- Generated by stele. Do not edit by hand - regenerate instead.\n"
    "     Source of truth: stele/tasks/*.md -->"
)

VALID_STATUS = {"todo", "in-progress", "blocked", "paused", "done"}
MAX_IN_PROGRESS = 3
MAX_OPEN_STEPS = 2
DONE_SHOWN = 20
SECTIONS = [
    ("in-progress", "Active"),
    ("todo", "Todo"),
    ("blocked", "Blocked"),
    ("paused", "Paused"),
]

def find_root(explicit: str | None) -> Path | None:
    """Locate the stele/ directory: explicit path, or walk up from cwd."""
    if explicit:
        p = Path(explicit).expanduser().resolve()
        if (p / "tasks").is_dir():
            return p
        if (p / "stele" / "tasks").is_dir():
            return p / "stele"
        return None
    here = Path.cwd().resolve()
    for d in [here, *here.parents]:
        if (d / "stele" / "tasks").is_dir():
            return d / "stele"
        if d.name == "stele" and (d / "tasks").is_dir():
            return d
    return None


def parse(path: Path) -> dict:
    """Read the six indexed fields and count open steps. Everything else is ignored."""
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    meta: dict[str, str] = {}
    malformed = True
    body = ""

    if lines and lines[0].strip() == "---":
        for i, line in enumerate(lines[1:], start=1):
            if line.strip() == "---":
                malformed = False
                body = "\n".join(lines[i + 1 :])
                break
            key, sep, value = line.partition(":")
            if sep and key.strip() in FIELDS:
                meta[key.strip()] = value.strip().strip("\"'")

    return {
        "path": path,
        "meta": meta,
        "malformed": malformed,
        "id": meta.get("id", path.stem),
        "title": meta.get("title", path.stem),
        "status": meta.get("status", "").lower(),
        "by": meta.get("last_modified_by", ""),
        "updated_at": meta.get("updated_at", ""),
        "open_steps": len(OPEN_STEP.findall(body)),
    }


def load(directory: Path) -> list[dict]:
    if not directory.is_dir():
        return []
    return [parse(p) for p in sorted(directory.glob("*.md"))]


def render(live: list[dict], done: list[dict]) -> str:
    out = [HEADER, "", "# Tasks", ""]

    for status, heading in SECTIONS:
        rows = [t for t in live if t["status"] == status]
        rows.sort(key=lambda t: t["updated_at"], reverse=(status == "in-progress"))
        out += [f"## {heading}", ""]
        if not rows:
            out += ["_none_", ""]
            continue
        for t in rows:
            flag = "[!] " if t["open_steps"] else ""
            out.append(f"- {flag}**{t['id']}** - {t['title']}")
            trail = " · ".join(x for x in (t["by"], t["updated_at"]) if x)
            if status == "in-progress" and trail:
                out.append(f"    {trail}")
        out.append("")

    ordered = sorted(done, key=lambda t: t["updated_at"], reverse=True)
    out += ["## Done", ""]
    if not ordered:
        out += ["_none_", ""]
    else:
        for t in ordered[:DONE_SHOWN]:
            trail = " · ".join(x for x in (t["by"], t["updated_at"]) if x)
            out.append(f"- **{t['id']}** - {t['title']}" + (f" · {trail}" if trail else ""))
        if len(ordered) > DONE_SHOWN:
            out.append(f"- _...{len(ordered) - DONE_SHOWN} older, in `tasks/done/`_")
        out.append("")

    out += [
        "---",
        "",
        "Open task files only for what is Active. `tasks/done/` is listed here so you know what "
        "has been done without reading it.",
    ]
    return "\n".join(out).rstrip() + "\n"


def validate(live: list[dict], done: list[dict]) -> list[str]:
    problems: list[str] = []
    seen: dict[str, str] = {}

    for t in live + done:
        name = t["path"].name

        if t["malformed"]:
            problems.append(
                f"ERROR {name}: frontmatter has no closing `---`. This is what a torn write looks "
                "like - repair it before trusting anything about this task."
            )
        for key in ("id", "title", "status"):
            if not t["meta"].get(key):
                problems.append(f"ERROR {name}: missing frontmatter key `{key}`")
        if t["status"] and t["status"] not in VALID_STATUS:
            problems.append(
                f"ERROR {name}: status `{t['status']}` is not one of {sorted(VALID_STATUS)}"
            )
        stem_num = re.match(r"(\d+)", t["path"].stem)
        id_num = re.search(r"(\d+)", t["id"])
        if stem_num and id_num and stem_num.group(1).lstrip("0") != id_num.group(1).lstrip("0"):
            problems.append(
                f"WARN  {name}: filename says {stem_num.group(1)} but id is `{t['id']}` - "
                "they should agree, or cross-references go to the wrong file"
            )
        if t["id"] in seen:
            problems.append(f"ERROR {name}: duplicate id `{t['id']}` (also {seen[t['id']]})")
        seen[t["id"]] = name

    for t in live:
        name = t["path"].name
        if t["open_steps"] > MAX_OPEN_STEPS:
            problems.append(
                f"ERROR {name}: {t['open_steps']} steps marked [open] (max {MAX_OPEN_STEPS}). "
                "Close one before opening another."
            )
        if t["status"] != "in-progress" and t["open_steps"]:
            problems.append(
                f"ERROR {name}: status `{t['status'] or '?'}` but a step is still open - the tree "
                "may be mid-edit and the next agent will skip straight past it. Close the step "
                "before parking or closing the task."
            )
        if t["status"] == "done":
            problems.append(f"WARN  {name}: status done but still in tasks/ - move it to tasks/done/")
        if t["status"] == "in-progress":
            if not t["updated_at"]:
                problems.append(f"WARN  {name}: in-progress with no `updated_at`")
            if not t["by"]:
                problems.append(f"WARN  {name}: in-progress with no `last_modified_by`")

    active = sum(1 for t in live if t["status"] == "in-progress")
    if active > MAX_IN_PROGRESS:
        problems.append(
            f"ERROR {active} tasks in-progress (max {MAX_IN_PROGRESS}). Park one with status: paused."
        )
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate stele/TASKS.md and validate invariants.")
    ap.add_argument("--root", help="path to the stele/ directory")
    ap.add_argument("--check", action="store_true", help="do not write; exit 1 on drift or errors")
    args = ap.parse_args()

    root = find_root(args.root)
    if root is None:
        print(
            "stele: no stele/tasks directory found - run from a project that has been "
            "bootstrapped, or pass --root",
            file=sys.stderr,
        )
        return 2

    live = load(root / "tasks")
    done = load(root / "tasks" / "done")

    problems = validate(live, done)
    errors = [p for p in problems if p.startswith("ERROR")]
    rendered = render(live, done)
    index = root / "TASKS.md"
    current = index.read_text(encoding="utf-8") if index.exists() else ""
    drifted = current != rendered

    for p in problems:
        print(p, file=sys.stderr)

    if args.check:
        if drifted:
            print("ERROR TASKS.md is stale - regenerate it (run without --check)", file=sys.stderr)
        return 1 if (drifted or errors) else 0

    if drifted:
        index.write_text(rendered, encoding="utf-8")
        print(f"stele: wrote {index}")
    else:
        print(f"stele: {index} already current")

    active = sum(1 for t in live if t["status"] == "in-progress")
    print(f"stele: {len(live)} live task(s), {active} in-progress, {len(done)} done")
    if problems:
        print(
            f"stele: {len(errors)} error(s), {len(problems) - len(errors)} warning(s) above - the "
            "index was still written; use --check in CI to gate on them"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
