#!/usr/bin/env python3
"""stele - regenerate TASKS.md from task files, and validate the invariants.

Task files are the source of truth. TASKS.md is a rendered index; fix drift by
regenerating it, never by editing it.

Usage:
    python3 stele/bin/index.py              regenerate stele/TASKS.md
    python3 stele/bin/index.py --check      exit 1 if stale or invariants are broken
    python3 stele/bin/index.py --root PATH  point at a stele/ directory explicitly
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

OPEN_MARKER = re.compile(r"\[\s*open\s*\]", re.IGNORECASE)

HEADER = (
    "<!-- Generated by stele/bin/index.py. Do not edit by hand - regenerate instead.\n"
    "     Source of truth: stele/tasks/*.md -->"
)

VALID_STATUS = {"todo", "in-progress", "blocked", "paused", "done"}
MAX_IN_PROGRESS = 3
SECTIONS = [
    ("in-progress", "Active"),
    ("todo", "Todo"),
    ("blocked", "Blocked"),
    ("paused", "Paused"),
]


# --------------------------------------------------------------------------- io


def find_root(explicit: str | None) -> Path | None:
    """Locate the stele/ directory: explicit path, or walk up from cwd."""
    if explicit:
        p = Path(explicit).expanduser().resolve()
        if (p / "tasks").is_dir():
            return p
        if (p / "stele" / "tasks").is_dir():
            return p / "stele"
        return None
    here = Path.cwd().resolve()
    for d in [here, *here.parents]:
        if (d / "stele" / "tasks").is_dir():
            return d / "stele"
        if d.name == "stele" and (d / "tasks").is_dir():
            return d
    return None


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Flat `key: value` pairs from a leading --- block. Nested keys are ignored."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    meta: dict[str, str] = {}
    end = len(lines)
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = i
            break
        if not line.strip() or line.startswith((" ", "\t", "-", "#")):
            continue  # nested block or comment; not a flat scalar
        if ":" in line:
            key, _, value = line.partition(":")
            meta[key.strip()] = value.strip().strip("\"'")
    return meta, "\n".join(lines[end + 1 :])


def open_step(body: str) -> dict[str, str] | None:
    """Return the open step's heading and its bullet fields, if any step is open."""
    lines = body.splitlines()
    in_steps = False
    current: dict[str, str] | None = None
    last_key: str | None = None
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("## "):
            in_steps = stripped[3:].strip().lower().startswith("steps")
            if current:
                return current
            continue
        if not in_steps:
            continue
        if stripped.startswith("### "):
            if current:
                return current
            heading = stripped[4:].strip()
            if OPEN_MARKER.search(heading):
                current = {"step": OPEN_MARKER.sub("", heading).strip()}
            continue
        if current is None:
            continue
        if stripped.startswith("- ") and ":" in stripped:
            key, _, value = stripped[2:].partition(":")
            last_key = key.strip().lower()
            current.setdefault(last_key, value.strip())
        elif stripped and last_key and not stripped.startswith(("-", "#", "|")):
            # wrapped continuation of the previous bullet - join rather than truncate
            current[last_key] = f"{current[last_key]} {stripped}".strip()
    return current


def load_tasks(root: Path) -> list[dict]:
    tasks = []
    for path in sorted((root / "tasks").glob("*.md")):
        text = path.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(text)
        tasks.append(
            {
                "path": path,
                "meta": meta,
                "id": meta.get("id", path.stem),
                "title": meta.get("title", path.stem),
                "status": meta.get("status", "").lower(),
                "owner": meta.get("owner", ""),
                "updated_at": meta.get("updated_at", ""),
                "open_step": open_step(body),
            }
        )
    return tasks


# ---------------------------------------------------------------------- render


def render(tasks: list[dict], archived: int) -> str:
    out = [HEADER, "", "# Tasks", ""]
    for status, heading in SECTIONS:
        rows = [t for t in tasks if t["status"] == status]
        rows.sort(key=lambda t: t["updated_at"], reverse=(status == "in-progress"))
        out.append(f"## {heading}")
        out.append("")
        if not rows:
            out.append("_none_")
            out.append("")
            continue
        for t in rows:
            step = t["open_step"]
            flag = "[!] " if step else ""
            out.append(f"- {flag}**{t['id']}** - {t['title']}")
            if status != "in-progress" and step:
                out.append(
                    f"    open step left behind: {step.get('step', '?')} - "
                    "tree may be mid-surgery, reconcile before skipping this"
                )
            if status == "in-progress":
                bits = []
                if step:
                    bits.append(f"step open: {step.get('step', '?')}")
                    if step.get("anchor"):
                        bits.append(f"anchor {step['anchor']}")
                else:
                    bits.append("no open step")
                if t["owner"]:
                    bits.append(t["owner"])
                if t["updated_at"]:
                    bits.append(t["updated_at"])
                out.append(f"    {' · '.join(bits)}")
                nxt = (step or {}).get("intent") or (step or {}).get("next")
                if nxt:
                    out.append(f"    next: {nxt}")
                if (step or {}).get("caveat"):
                    out.append(f"    caveat: {step['caveat']}")
            elif t["meta"].get("blocked_on"):
                out.append(f"    blocked on: {t['meta']['blocked_on']}")
        out.append("")
    out.append("---")
    out.append("")
    out.append(
        f"{archived} archived. Do not read `tasks/archive/` during a resume - "
        "search it only when hunting specific history."
    )
    return "\n".join(out).rstrip() + "\n"


# -------------------------------------------------------------------- validate


def validate(tasks: list[dict]) -> list[str]:
    problems: list[str] = []
    seen: dict[str, Path] = {}

    for t in tasks:
        name = t["path"].name
        for key in ("id", "title", "status"):
            if not t["meta"].get(key):
                problems.append(f"ERROR {name}: missing frontmatter key `{key}`")
        if t["status"] and t["status"] not in VALID_STATUS:
            problems.append(
                f"ERROR {name}: status `{t['status']}` is not one of {sorted(VALID_STATUS)}"
            )
        if t["id"] in seen:
            problems.append(f"ERROR {name}: duplicate id `{t['id']}` (also {seen[t['id']].name})")
        seen[t["id"]] = t["path"]

        if t["status"] == "in-progress":
            if not t["owner"]:
                problems.append(f"ERROR {name}: in-progress with no `owner` - cannot lease")
            if not t["updated_at"]:
                problems.append(f"ERROR {name}: in-progress with no `updated_at` - lease cannot go stale")
        elif t["open_step"]:
            problems.append(
                f"ERROR {name}: status `{t['status'] or '?'}` but a step is still open - "
                "the tree may be mid-surgery and the next agent will skip past it. "
                "Close the step before parking or closing the task."
            )

        if t["status"] == "done":
            problems.append(f"WARN  {name}: status done but still in tasks/ - move it to tasks/archive/")

        if t["open_step"] and not t["open_step"].get("verify"):
            problems.append(f"WARN  {name}: open step has no `verify:` - nothing can prove it finished")

    active = [t for t in tasks if t["status"] == "in-progress"]
    if len(active) > MAX_IN_PROGRESS:
        problems.append(
            f"ERROR {len(active)} tasks in-progress (max {MAX_IN_PROGRESS}). "
            "Park one with status: paused."
        )
    owners: dict[str, str] = {}
    for t in active:
        if t["owner"] and t["owner"] in owners:
            problems.append(
                f"ERROR {t['path'].name}: owner `{t['owner']}` already holds {owners[t['owner']]} - "
                "one in-progress task per owner"
            )
        owners[t["owner"]] = t["id"]
    return problems


# ------------------------------------------------------------------------ main


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", help="path to the stele/ directory")
    ap.add_argument("--check", action="store_true", help="do not write; exit 1 on drift or errors")
    args = ap.parse_args()

    root = find_root(args.root)
    if root is None:
        print("stele: no stele/tasks directory found (run scripts/install.py first)", file=sys.stderr)
        return 2

    tasks = load_tasks(root)
    archive = root / "tasks" / "archive"
    archived = len(list(archive.glob("*.md"))) if archive.is_dir() else 0

    problems = validate(tasks)
    rendered = render(tasks, archived)
    index = root / "TASKS.md"
    current = index.read_text(encoding="utf-8") if index.exists() else ""
    drifted = current != rendered

    for p in problems:
        print(p, file=sys.stderr)

    if args.check:
        if drifted:
            print("ERROR TASKS.md is stale - run `python3 stele/bin/index.py`", file=sys.stderr)
        return 1 if (drifted or any(p.startswith("ERROR") for p in problems)) else 0

    if drifted:
        index.write_text(rendered, encoding="utf-8")
        print(f"stele: wrote {index}")
    else:
        print(f"stele: {index} already current")

    active = [t for t in tasks if t["status"] == "in-progress"]
    print(f"stele: {len(tasks)} live task(s), {len(active)} in-progress, {archived} archived")
    return 1 if any(p.startswith("ERROR") for p in problems) else 0


if __name__ == "__main__":
    sys.exit(main())
