#!/usr/bin/env python3
"""stele - regenerate TASKS.md from task files, and validate the invariants.

Task files are the source of truth. TASKS.md is a rendered index; fix drift by
regenerating it, never by editing it.

Usage:
    python3 index.py                          regenerate, finding stele/ upward from cwd
    python3 index.py --root ./stele           point at a stele/ directory explicitly
    python3 index.py --root ./stele --check   exit 1 on drift or a broken invariant

Exit codes: the regenerate path exits 0 when it wrote successfully, reporting any problems
as text. `--check` is the gate that exits non-zero - use it in CI.

An accelerator, not a dependency: an agent that cannot locate this script maintains
TASKS.md by hand from the shape documented in SKILL.md.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

OPEN_MARKER = re.compile(r"\[\s*open\s*\]", re.IGNORECASE)

HEADER = (
    "<!-- Generated by stele. Do not edit by hand - regenerate instead.\n"
    "     Source of truth: stele/tasks/*.md -->"
)

VALID_STATUS = {"todo", "in-progress", "blocked", "paused", "done"}
MAX_IN_PROGRESS = 3
SECTIONS = [
    ("in-progress", "Active"),
    ("todo", "Todo"),
    ("blocked", "Blocked"),
    ("paused", "Paused"),
]


# --------------------------------------------------------------------------- io


def find_root(explicit: str | None) -> Path | None:
    """Locate the stele/ directory: explicit path, or walk up from cwd."""
    if explicit:
        p = Path(explicit).expanduser().resolve()
        if (p / "tasks").is_dir():
            return p
        if (p / "stele" / "tasks").is_dir():
            return p / "stele"
        return None
    here = Path.cwd().resolve()
    for d in [here, *here.parents]:
        if (d / "stele" / "tasks").is_dir():
            return d / "stele"
        if d.name == "stele" and (d / "tasks").is_dir():
            return d
    return None


def parse_frontmatter(text: str) -> tuple[dict[str, str], str, bool]:
    """Flat `key: value` pairs from a leading --- block. Nested keys are ignored.

    Returns (meta, body, malformed). `malformed` is True when there is no closing
    `---`, which is what a torn write during a frontmatter update looks like. That
    case must never be mistaken for "a task with no steps".
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text, True
    meta: dict[str, str] = {}
    end: int | None = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = i
            break
        if not line.strip() or line.startswith((" ", "\t", "-", "#")):
            continue  # nested block or comment, not a flat scalar
        if ":" in line:
            key, _, value = line.partition(":")
            meta[key.strip()] = value.strip().strip("\"'")
    if end is None:
        return meta, "", True
    return meta, "\n".join(lines[end + 1 :]), False


def parse_steps(body: str) -> tuple[dict[str, str] | None, int, bool]:
    """Return (first open step, count of open steps, saw a `## Steps` heading).

    The third value matters: a task whose steps live under some other heading -
    `## Step log`, say - would otherwise look like a task with nothing open, and
    the whole resume procedure keys off whether a step is open.
    """
    lines = body.splitlines()
    in_steps = False
    saw_steps_heading = False
    first: dict[str, str] | None = None
    current: dict[str, str] | None = None
    open_count = 0
    last_key: str | None = None

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("## "):
            in_steps = stripped[3:].strip().lower().startswith("steps")
            saw_steps_heading = saw_steps_heading or in_steps
            if current and first is None:
                first = current
            current = None
            last_key = None
            continue

        if not in_steps:
            continue

        if stripped.startswith("### "):
            if current and first is None:
                first = current
            current = None
            last_key = None
            heading = stripped[4:].strip()
            if OPEN_MARKER.search(heading):
                open_count += 1
                current = {"step": OPEN_MARKER.sub("", heading).strip()}
            continue

        if current is None:
            continue
        if stripped.startswith("- ") and ":" in stripped:
            key, _, value = stripped[2:].partition(":")
            last_key = key.strip().lower()
            current.setdefault(last_key, value.strip())
        elif stripped and last_key and not stripped.startswith(("-", "#", "|")):
            # wrapped continuation of the previous bullet - join rather than truncate
            current[last_key] = f"{current[last_key]} {stripped}".strip()

    if current and first is None:
        first = current
    return first, open_count, saw_steps_heading


def looks_like_steps_heading(body: str) -> str | None:
    """A `## ...step...` heading that is not `## Steps` - the silent-failure case."""
    for line in body.splitlines():
        s = line.strip()
        if s.startswith("## ") and "step" in s.lower():
            if not s[3:].strip().lower().startswith("steps"):
                return s[3:].strip()
    return None


def load_tasks(root: Path) -> list[dict]:
    tasks = []
    for path in sorted((root / "tasks").glob("*.md")):
        meta, body, malformed = parse_frontmatter(path.read_text(encoding="utf-8"))
        step, open_count, saw_steps = parse_steps(body)
        tasks.append(
            {
                "path": path,
                "meta": meta,
                "malformed": malformed,
                "id": meta.get("id", path.stem),
                "title": meta.get("title", path.stem),
                "status": meta.get("status", "").lower(),
                "by": meta.get("last_modified_by", ""),
                "updated_at": meta.get("updated_at", ""),
                "open_step": step,
                "open_count": open_count,
                "saw_steps": saw_steps,
                "odd_heading": looks_like_steps_heading(body),
            }
        )
    return tasks


# ---------------------------------------------------------------------- render


def render(tasks: list[dict], archived: int) -> str:
    out = [HEADER, "", "# Tasks", ""]
    for status, heading in SECTIONS:
        rows = [t for t in tasks if t["status"] == status]
        rows.sort(key=lambda t: t["updated_at"], reverse=(status == "in-progress"))
        out += [f"## {heading}", ""]
        if not rows:
            out += ["_none_", ""]
            continue
        for t in rows:
            step = t["open_step"]
            flag = "[!] " if step else ""
            out.append(f"- {flag}**{t['id']}** - {t['title']}")
            if status != "in-progress" and step:
                out.append(
                    f"    open step left behind: {step.get('step', '?')} - "
                    "tree may be mid-edit, reconcile before skipping this"
                )
            if status == "in-progress":
                bits = []
                if step:
                    bits.append(f"step open: {step.get('step', '?')}")
                    if step.get("anchor"):
                        bits.append(f"from {step['anchor']}")
                else:
                    bits.append("no open step")
                if t["by"]:
                    bits.append(t["by"])
                if t["updated_at"]:
                    bits.append(t["updated_at"])
                out.append(f"    {' · '.join(bits)}")
                if (step or {}).get("intent"):
                    out.append(f"    next: {step['intent']}")
                if (step or {}).get("files"):
                    out.append(f"    mid-edit: {step['files']}")
                if (step or {}).get("caveat"):
                    out.append(f"    caveat: {step['caveat']}")
            elif t["meta"].get("blocked_on"):
                out.append(f"    blocked on: {t['meta']['blocked_on']}")
        out.append("")
    out += [
        "---",
        "",
        f"{archived} done. Do not read `tasks/done/` during a resume - "
        "search it only when hunting specific history.",
    ]
    return "\n".join(out).rstrip() + "\n"


# -------------------------------------------------------------------- validate


def validate(tasks: list[dict]) -> list[str]:
    problems: list[str] = []
    seen: dict[str, Path] = {}

    for t in tasks:
        name = t["path"].name

        if t["malformed"]:
            problems.append(
                f"ERROR {name}: frontmatter has no closing `---`. This is what a torn write "
                "looks like; the body cannot be parsed, so an open step here would be "
                "invisible. Repair the file before trusting anything about this task."
            )

        for key in ("id", "title", "status"):
            if not t["meta"].get(key):
                problems.append(f"ERROR {name}: missing frontmatter key `{key}`")
        if t["status"] and t["status"] not in VALID_STATUS:
            problems.append(
                f"ERROR {name}: status `{t['status']}` is not one of {sorted(VALID_STATUS)}"
            )
        if t["id"] in seen:
            problems.append(f"ERROR {name}: duplicate id `{t['id']}` (also {seen[t['id']].name})")
        seen[t["id"]] = t["path"]

        if t["status"] != "in-progress" and t["open_step"]:
            problems.append(
                f"ERROR {name}: status `{t['status'] or '?'}` but a step is still open - the "
                "tree may be mid-edit and the next agent will skip straight past it. Close "
                "the step before parking or closing the task."
            )

        if t["open_count"] > 1:
            problems.append(
                f"ERROR {name}: {t['open_count']} steps marked [open]. Only one step may be "
                "open; the resume procedure cannot tell which one is current."
            )

        if t["odd_heading"] and not t["saw_steps"]:
            problems.append(
                f"ERROR {name}: steps appear to live under `## {t['odd_heading']}` rather than "
                "`## Steps`. Nothing under it is parsed, so an open step is invisible here."
            )

        if t["status"] == "in-progress":
            if not t["updated_at"]:
                problems.append(
                    f"WARN  {name}: in-progress with no `updated_at` - freshness cannot be judged"
                )
            if not t["by"]:
                problems.append(f"WARN  {name}: in-progress with no `last_modified_by`")

        if t["status"] == "done":
            problems.append(f"WARN  {name}: status done but still in tasks/ - move it to tasks/done/")

    active = [t for t in tasks if t["status"] == "in-progress"]
    if len(active) > MAX_IN_PROGRESS:
        problems.append(
            f"ERROR {len(active)} tasks in-progress (max {MAX_IN_PROGRESS}). "
            "Park one with status: paused."
        )
    return problems


# ------------------------------------------------------------------------ main


def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate stele/TASKS.md and validate invariants.")
    ap.add_argument("--root", help="path to the stele/ directory")
    ap.add_argument("--check", action="store_true", help="do not write; exit 1 on drift or errors")
    args = ap.parse_args()

    root = find_root(args.root)
    if root is None:
        print(
            "stele: no stele/tasks directory found - run from a project that has been "
            "bootstrapped, or pass --root",
            file=sys.stderr,
        )
        return 2

    tasks = load_tasks(root)
    done_dir = root / "tasks" / "done"
    archived = len(list(done_dir.glob("*.md"))) if done_dir.is_dir() else 0

    problems = validate(tasks)
    errors = [p for p in problems if p.startswith("ERROR")]
    rendered = render(tasks, archived)
    index = root / "TASKS.md"
    current = index.read_text(encoding="utf-8") if index.exists() else ""
    drifted = current != rendered

    for p in problems:
        print(p, file=sys.stderr)

    if args.check:
        if drifted:
            print(
                "ERROR TASKS.md is stale - regenerate it (run without --check)", file=sys.stderr
            )
        return 1 if (drifted or errors) else 0

    if drifted:
        index.write_text(rendered, encoding="utf-8")
        print(f"stele: wrote {index}")
    else:
        print(f"stele: {index} already current")

    active = sum(1 for t in tasks if t["status"] == "in-progress")
    print(f"stele: {len(tasks)} live task(s), {active} in-progress, {archived} done")
    if problems:
        print(
            f"stele: {len(errors)} error(s), {len(problems) - len(errors)} warning(s) above - "
            "the index was still written; use --check in CI to gate on them"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
